// This file contains a pre-generated dataset for the Smart Advisor's Crop Selection quiz.
// It maps every combination of season, soil, irrigation, and farm size to a specific recommendation.
// Key format: "Season_Soil_Irrigation_Size"

export const cropAdvisorDataset: { [key: string]: string } = {
  "Monsoon_Clay_Yes_<2": "Suitable crops: Paddy, Vegetables (Okra). Tip: High-value vegetable farming is profitable on small plots.",
  "Monsoon_Clay_Yes_2-5": "Suitable crops: Paddy, Sugarcane, Soybean. Tip: Crop rotation is key to maintaining soil health.",
  "Monsoon_Clay_Yes_>5": "Suitable crops: Paddy, Sugarcane. Tip: Ideal for mechanised farming of water-intensive crops.",
  "Monsoon_Clay_No_<2": "Suitable crops: Paddy (rain-fed), Maize, Black Gram. Tip: Bunding helps retain rainwater effectively.",
  "Monsoon_Clay_No_2-5": "Suitable crops: Paddy (rain-fed), Maize, Soybean. Tip: Clay's water retention is excellent for rain-fed agriculture.",
  "Monsoon_Clay_No_>5": "Suitable crops: Paddy (rain-fed), Maize, Sorghum. Tip: Focus on drought-resistant varieties for large-scale rain-fed farming.",
  "Monsoon_Sandy_Yes_<2": "Suitable crops: Bajra, Groundnut, Vegetables (Cucumber). Tip: Drip irrigation is essential to save water and fertilizer.",
  "Monsoon_Sandy_Yes_2-5": "Suitable crops: Bajra, Groundnut, Maize. Tip: Sprinkler irrigation can cover medium plots efficiently.",
  "Monsoon_Sandy_Yes_>5": "Suitable crops: Bajra, Groundnut, Cotton. Tip: Large scale drip irrigation is a worthwhile investment.",
  "Monsoon_Sandy_No_<2": "Suitable crops: Bajra, Moong (Green Gram), Moth Bean. Tip: Focus on extremely drought-tolerant pulses.",
  "Monsoon_Sandy_No_2-5": "Suitable crops: Bajra, Guar, Cowpea. Tip: Intercropping with legumes improves soil fertility.",
  "Monsoon_Sandy_No_>5": "Suitable crops: Bajra, Guar. Tip: Minimal tillage is recommended to conserve soil moisture.",
  "Monsoon_Loamy_Yes_<2": "Suitable crops: Paddy, Vegetables (Tomato, Brinjal), Soybean. Tip: Intercropping vegetables with soybeans is highly profitable.",
  "Monsoon_Loamy_Yes_2-5": "Suitable crops: Paddy, Cotton, Soybean, Maize. Tip: Can diversify with cash crops like Turmeric.",
  "Monsoon_Loamy_Yes_>5": "Suitable crops: Paddy, Cotton, Soybean. Tip: Loamy soil supports a wide range of mechanized commercial crops.",
  "Monsoon_Loamy_No_<2": "Suitable crops: Maize, Groundnut, Pigeon Pea (Arhar). Tip: Planting on ridges ensures good drainage during heavy rain.",
  "Monsoon_Loamy_No_2-5": "Suitable crops: Maize, Soybean, Groundnut, Sorghum. Tip: A balanced soil that performs well even in rain-fed conditions.",
  "Monsoon_Loamy_No_>5": "Suitable crops: Maize, Soybean, Sorghum. Tip: Good drainage is natural, reducing risk of crop failure in heavy monsoon.",
  "Winter_Clay_Yes_<2": "Suitable crops: Wheat, Vegetables (Peas, Cabbage), Berseem (fodder). Tip: Excellent for high-yield wheat and fodder for livestock.",
  "Winter_Clay_Yes_2-5": "Suitable crops: Wheat, Sugarcane, Mustard. Tip: The soil's high water retention reduces irrigation frequency.",
  "Winter_Clay_Yes_>5": "Suitable crops: Wheat, Sugarcane. Tip: Heavy soil is ideal for large-scale mechanized wheat harvesting.",
  "Winter_Clay_No_<2": "Suitable crops: Chickpea (Gram), Lentil, Linseed. Tip: Sow early to utilize maximum residual moisture from monsoon.",
  "Winter_Clay_No_2-5": "Suitable crops: Chickpea, Lentil, Safflower. Tip: Deep tillage can help plant roots access moisture stored in the soil.",
  "Winter_Clay_No_>5": "Suitable crops: Chickpea, Lentil. Tip: Zero tillage is a great technique to conserve moisture for large farms.",
  "Winter_Sandy_Yes_<2": "Suitable crops: Mustard, Barley, Vegetables (Carrot, Radish). Tip: Frequent, light irrigation is key to prevent water from draining away.",
  "Winter_Sandy_Yes_2-5": "Suitable crops: Wheat, Mustard, Barley. Tip: Sprinkler irrigation is more efficient than flood irrigation here.",
  "Winter_Sandy_Yes_>5": "Suitable crops: Wheat, Mustard. Tip: Large investment in sprinkler or drip systems is necessary for good yields.",
  "Winter_Sandy_No_<2": "Suitable crops: Chickpea, Mustard (drought-tolerant vars). Avoid wheat. Tip: Use mulching with straw to conserve precious water.",
  "Winter_Sandy_No_2-5": "Suitable crops: Chickpea, Barley. Tip: Extremely challenging; select only the most drought-hardy varieties.",
  "Winter_Sandy_No_>5": "Suitable crops: Barley. Tip: Very high risk. Consider leaving land fallow to conserve resources for Kharif.",
  "Winter_Loamy_Yes_<2": "Suitable crops: Wheat, Potato, Vegetables (Onion, Garlic). Tip: Ideal soil for high-value winter vegetables on a small plot.",
  "Winter_Loamy_Yes_2-5": "Suitable crops: Wheat, Potato, Mustard, Gram. Tip: Allows for a diverse and profitable crop mix.",
  "Winter_Loamy_Yes_>5": "Suitable crops: Wheat, Potato, Mustard. Tip: Perfect conditions for large-scale commercial farming with high returns.",
  "Winter_Loamy_No_<2": "Suitable crops: Chickpea, Mustard, Lentil. Tip: Excellent returns with low input costs due to residual moisture.",
  "Winter_Loamy_No_2-5": "Suitable crops: Chickpea, Mustard, Linseed. Tip: Practice crop rotation with Kharif legumes to boost soil nitrogen.",
  "Winter_Loamy_No_>5": "Suitable crops: Chickpea, Mustard. Tip: Zero tillage on a large scale can significantly boost profitability.",
  "Summer_Clay_Yes_<2": "Suitable crops: Groundnut, Moong, Cowpea. Tip: Add gypsum to the soil to improve its structure and prevent cracking.",
  "Summer_Clay_Yes_2-5": "Suitable crops: Groundnut, Moong, Urad (Black Gram). Tip: Light and frequent irrigation is better than heavy, infrequent watering.",
  "Summer_Clay_Yes_>5": "Suitable crops: Groundnut, Sesamum. Tip: Plan land leveling to ensure uniform water distribution.",
  "Summer_Clay_No_<2": "Suitable crops: Fodder Sorghum (if early rains). Tip: Leaving the land fallow is the safest and best option to restore nutrients.",
  "Summer_Clay_No_2-5": "Suitable crops: Not recommended. Tip: Plough the field and leave it fallow to expose soil to the sun, killing pests.",
  "Summer_Clay_No_>5": "Suitable crops: Not recommended. Tip: This is a good time for soil testing and amendments for the coming monsoon season.",
  "Summer_Sandy_Yes_<2": "Suitable crops: Watermelon, Muskmelon, Cucumber. Tip: High-value cucurbits are perfect for small, irrigated sandy plots.",
  "Summer_Sandy_Yes_2-5": "Suitable crops: Watermelon, Muskmelon, Bajra (for fodder). Tip: Drip irrigation is almost essential to make summer cropping viable.",
  "Summer_Sandy_Yes_>5": "Suitable crops: Bajra. Tip: Large scale vegetable farming requires significant investment in micro-irrigation.",
  "Summer_Sandy_No_<2": "Suitable crops: Not feasible. Tip: Add organic matter like farmyard manure to improve soil water holding capacity for next season.",
  "Summer_Sandy_No_2-5": "Suitable crops: Not feasible. Tip: Consider growing green manure crops like Sunnhemp if there is some moisture.",
  "Summer_Sandy_No_>5": "Suitable crops: Not feasible. Tip: Use this time for land leveling and planning your water conservation structures.",
  "Summer_Loamy_Yes_<2": "Suitable crops: Moong, Groundnut, Vegetables (Okra, Pumpkin). Tip: Excellent for a quick, profitable pulse or vegetable crop before monsoon.",
  "Summer_Loamy_Yes_2-5": "Suitable crops: Moong, Groundnut, Maize (for fodder). Tip: Short-duration varieties are key to a successful summer crop.",
  "Summer_Loamy_Yes_>5": "Suitable crops: Moong, Groundnut. Tip: Large-scale pulse cultivation can be very profitable and improves soil nitrogen.",
  "Summer_Loamy_No_<2": "Suitable crops: Cowpea, Sesamum (if some rain). Tip: Very risky; only attempt with heat and drought-tolerant crops.",
  "Summer_Loamy_No_2-5": "Suitable crops: Not recommended. Tip: Leaving land fallow is the most common and wise practice.",
  "Summer_Loamy_No_>5": "Suitable crops: Not recommended. Tip: Focus on preparing the land for the main Kharif season sowing."
}
