// This file contains a pre-generated dataset for the Smart Advisor's Pest Diagnosis quiz.
// It maps every combination of crop, symptom, and time to a specific recommendation.
// Key format: "Crop_Symptom_Time"

export const pestAdvisorDataset: { [key: string]: string } = {
    "Paddy_Spots_<1week": "Likely Issue: Early stage of Brown Spot disease. Treatment: Spray a mild fungicide like Mancozeb. Tip: Ensure balanced nutrition to boost plant immunity.",
    "Paddy_Spots_1-2weeks": "Likely Issue: Developing Brown Spot or Blast disease. Treatment: Use a systemic fungicide like Tricyclazole. Tip: Avoid excess nitrogen fertilizer, which can make the disease worse.",
    "Paddy_Spots_>2weeks": "Likely Issue: Severe Brown Spot or Blast infection. Treatment: Immediate spray of Tricyclazole or a combination fungicide is critical. Tip: Remove and burn heavily infected plants to reduce spread.",
    "Paddy_Holes_<1week": "Likely Issue: Leaf Folder or Case Worm infestation. Treatment: Spray Chlorantraniliprole. Organic option: Neem oil. Tip: Look for folded leaves or caterpillar larvae.",
    "Paddy_Holes_1-2weeks": "Likely Issue: Established Leaf Folder or Stem Borer. Treatment: Use Fipronil granules in standing water for stem borer. Tip: Pheromone traps can help monitor pest population.",
    "Paddy_Holes_>2weeks": "Likely Issue: Severe Stem Borer damage ('dead heart' symptom). Treatment: Control is difficult at this stage. Apply Fipronil to protect remaining plants. Tip: Uproot and destroy plants showing 'dead heart' or 'white ear'.",
    "Paddy_Wilting_<1week": "Likely Issue: Bacterial Leaf Blight (BLB) or water stress. Treatment: Check soil moisture first. If moist, spray Streptomycin sulfate. Tip: Avoid irrigation during midday.",
    "Paddy_Wilting_1-2weeks": "Likely Issue: Advanced Bacterial Leaf Blight. Treatment: Spray a combination of Streptomycin and Copper Oxychloride. Tip: Ensure field drainage is not blocked.",
    "Paddy_Wilting_>2weeks": "Likely Issue: Severe BLB or potential root issue. Treatment: Management is critical. Use recommended bactericides. Tip: Avoid working in the field when foliage is wet to prevent spreading.",
    "Paddy_Insects_<1week": "Likely Issue: Brown Plant Hopper (BPH) or Green Leaf Hopper (GLH). Treatment: Spray Imidacloprid. Tip: Check the base of the plant near the water line for BPH.",
    "Paddy_Insects_1-2weeks": "Likely Issue: Growing population of Hoppers. Treatment: Use a stronger systemic insecticide like Thiamethoxam. Tip: Alternate insecticides to prevent resistance.",
    "Paddy_Insects_>2weeks": "Likely Issue: BPH outbreak ('hopper burn' may be visible). Treatment: Urgent action needed. Use Dinotefuran or Pymetrozine. Tip: Drain the field for a day before spraying for better results.",
    "Wheat_Spots_<1week": "Likely Issue: Yellow Rust or Powdery Mildew starting. Treatment: Spray Propiconazole at the first sign. Tip: Rust spreads fast, so early detection is key.",
    "Wheat_Spots_1-2weeks": "Likely Issue: Established Yellow Rust infection. Treatment: A timely spray of Propiconazole or Tebuconazole is effective. Tip: Ensure full coverage of the plant during spray.",
    "Wheat_Spots_>2weeks": "Likely Issue: Severe rust infection. Treatment: May require a second spray after 15 days. Tip: Avoid late irrigation as it can increase humidity and disease.",
    "Wheat_Holes_<1week": "Likely Issue: Armyworm or termite damage. Treatment: For armyworms, spray Chlorpyrifos in the evening. For termites, apply Fipronil with irrigation. Tip: Termites attack near the roots, check soil.",
    "Wheat_Holes_1-2weeks": "Likely Issue: Persistent armyworm issue. Treatment: Repeat spray if infestation continues. Tip: Look for caterpillar droppings on the ground.",
    "Wheat_Holes_>2weeks": "Likely Issue: Significant foliage damage. Treatment: Focus on protecting the flag leaf as it contributes most to grain filling. Tip: Ploughing after harvest destroys pupae in the soil.",
    "Wheat_Wilting_<1week": "Likely Issue: Water stress or potential root rot. Treatment: Check for soil moisture. If soil is wet, it could be root rot. Drench with a fungicide. Tip: Wilting in patches can indicate a soil-borne disease.",
    "Wheat_Wilting_1-2weeks": "Likely Issue: Fusarium root rot or termite damage. Treatment: Drench with Carbendazim for rot. Check for termites at the root zone. Tip: Good drainage is crucial to prevent root diseases.",
    "Wheat_Wilting_>2weeks": "Likely Issue: Severe root disease or nematode problem. Treatment: Control is very difficult. Minimize stress on the plant with light irrigation. Tip: Soil solarization in summer can reduce pathogens.",
    "Wheat_Insects_<1week": "Likely Issue: Aphids. Treatment: Spray a systemic insecticide like Imidacloprid. Organic option: ladybugs. Tip: Aphids are usually found on the ear heads and upper leaves.",
    "Wheat_Insects_1-2weeks": "Likely Issue: Established aphid colony. Treatment: Thiamethoxam spray will provide longer control. Tip: Yellow sticky traps can help in monitoring.",
    "Wheat_Insects_>2weeks": "Likely Issue: High aphid population, may see sooty mould. Treatment: A strong insecticide is needed. Tip: Heavy rain can wash away a significant portion of the aphid population.",
    "Tomato_Spots_<1week": "Likely Issue: Early Blight or Septoria Leaf Spot. Treatment: Remove lower affected leaves and spray Mancozeb. Tip: Mulching can prevent spores from splashing from the soil onto leaves.",
    "Tomato_Spots_1-2weeks": "Likely Issue: Advancing Early or Late Blight. Treatment: For Late Blight (water-soaked spots), use Metalaxyl + Mancozeb. Tip: Avoid overhead irrigation; use drip if possible.",
    "Tomato_Spots_>2weeks": "Likely Issue: Severe Blight infection. Treatment: Aggressive spray schedule with alternating fungicides is needed. Tip: Improve air circulation by pruning some branches.",
    "Tomato_Holes_<1week": "Likely Issue: Fruit Borer (Helicoverpa). Treatment: Spray Emamectin Benzoate. Organic: Bacillus thuringiensis (Bt). Tip: Look for small entry holes on fruits.",
    "Tomato_Holes_1-2weeks": "Likely Issue: Established Fruit Borer population. Treatment: A stronger insecticide may be needed. Tip: Pheromone traps are excellent for monitoring and mass trapping adult moths.",
    "Tomato_Holes_>2weeks": "Likely Issue: High fruit damage. Treatment: Collect and destroy all infected fruits. Spray to protect new fruits. Tip: Planting marigold as a trap crop can help.",
    "Tomato_Wilting_<1week": "Likely Issue: Bacterial Wilt or water stress. Treatment: Check soil moisture. If wet, it's likely Bacterial Wilt. No effective chemical control. Tip: Uproot and destroy wilting plants immediately to prevent spread.",
    "Tomato_Wilting_1-2weeks": "Likely Issue: Spreading Bacterial Wilt or Fusarium Wilt. Treatment: Drenching the soil around healthy plants with a bactericide might help. Tip: Do not plant tomato or brinjal in the same spot for 3 years.",
    "Tomato_Wilting_>2weeks": "Likely Issue: Widespread wilt disease. Treatment: The field is likely heavily infected. Focus on saving any remaining healthy plants. Tip: Use resistant varieties or grafted plants for the next season.",
    "Tomato_Insects_<1week": "Likely Issue: Whiteflies or Aphids. Treatment: Spray Imidacloprid or Acetamiprid. Organic: Yellow sticky traps and Neem oil. Tip: Whiteflies are vectors for many viral diseases.",
    "Tomato_Insects_1-2weeks": "Likely Issue: Growing Whitefly population. Treatment: Use Diafenthiuron. Tip: Ensure good coverage under the leaves.",
    "Tomato_Insects_>2weeks": "Likely Issue: High insect pressure, potential for virus transmission. Treatment: Strong control measures are needed. Tip: Remove and destroy any plants showing signs of leaf curl virus.",
    "Cotton_Spots_<1week": "Likely Issue: Alternaria Leaf Spot or Bacterial Blight. Treatment: Spray a copper-based fungicide like Copper Oxychloride. Tip: Use disease-free certified seeds.",
    "Cotton_Spots_1-2weeks": "Likely Issue: Developing fungal or bacterial disease. Treatment: A combination spray might be needed. Tip: Good drainage and air circulation are important.",
    "Cotton_Spots_>2weeks": "Likely Issue: Severe infection, may cause leaf drop. Treatment: Follow recommended spray schedule for your region. Tip: Proper disposal of plant debris after harvest reduces disease next season.",
    "Cotton_Holes_<1week": "Likely Issue: American Bollworm or Spotted Bollworm. Treatment: Spray Emamectin Benzoate. Tip: Monitor for eggs on young leaves and squares.",
    "Cotton_Holes_1-2weeks": "Likely Issue: Bollworm infestation. Treatment: Use Chlorantraniliprole. Tip: Pheromone traps are essential for monitoring bollworm moths.",
    "Cotton_Holes_>2weeks": "Likely Issue: Severe boll damage ('flaring' of squares). Treatment: Collect and destroy flared squares and damaged bolls. Tip: Bt cotton provides resistance but scouting is still necessary.",
    "Cotton_Wilting_<1week": "Likely Issue: Water stress or Root Rot. Treatment: Check soil moisture. If soil is wet, drench with a fungicide. Tip: Avoid excessive irrigation as it promotes root rot.",
    "Cotton_Wilting_1-2weeks": "Likely Issue: Fusarium or Verticillium Wilt. Treatment: No chemical cure. Manage by reducing plant stress. Tip: These diseases show as yellowing on one side of the leaf first.",
    "Cotton_Wilting_>2weeks": "Likely Issue: Advanced Wilt disease. Treatment: Uproot and destroy heavily infected plants. Tip: Deep summer ploughing can help reduce soil-borne pathogens.",
    "Cotton_Insects_<1week": "Likely Issue: Jassids or Aphids. Treatment: Spray Imidacloprid. Tip: Look for downward curling of leaves for Jassids.",
    "Cotton_Insects_1-2weeks": "Likely Issue: Jassids, Aphids or Whiteflies. Treatment: Use Acetamiprid or Diafenthiuron. Tip: Hairy cotton varieties are more resistant to Jassids.",
    "Cotton_Insects_>2weeks": "Likely Issue: High sucking pest complex. Treatment: A strong systemic insecticide is needed. Tip: Sticky traps can help control whitefly population."
}
